name: Sync Scaffolding Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
      - '.github/scripts/sync-repos.sh'
  workflow_dispatch: # Allows triggering the sync manually from the Actions tab

permissions:
  contents: read

jobs:
  sync-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@de0fac26c92973e3d937129bcbf40652eb9f2f61 # v6.0.2
        with:
          persist-credentials: false

      - name: Make sync script executable
        run: chmod +x .github/scripts/sync-repos.sh

      - name: Run synchronization script
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: .github/scripts/sync-repos.sh
